#ifndef WINDOWS_SIMULATION_FUSION_PROFILE_H
#define WINDOWS_SIMULATION_FUSION_PROFILE_H

#include <vector>

struct FusionProfileNode {
    float z = 0.0f;
    float r = 0.0f;
    float vz = 0.0f;
    float vr = 0.0f;
    float mass = 1.0f;
    float curvature = 0.0f;
    // Last physical normal force, retained for diagnostics/rendering only.
    float normalForceZ = 0.0f;
    float normalForceR = 0.0f;
    float volumeCorrection = 0.0f;

    // Lagrangian optical coordinates transported with this material ring.
    float filmAxial = 0.0f;
    float filmRadial = 1.0f;
    float opticalRadiusScale = 1.0f;

    // Initial position is diagnostic-only; it is never used as an animation
    // target.  It lets trajectory capture prove temporal continuity.
    float initialZ = 0.0f;
    float initialR = 0.0f;
};

struct FusionProfileConfig {
    // Equivalent surface tension multiplying the area gradient.
    float surfaceTension = 0.180f;
    // Viscous damping rate applied to material velocity.
    float velocityDamping = 1.00f;
    // Meridian viscosity damps grid-scale velocity without suppressing the
    // low capillary mode as strongly as uniform drag.
    float velocityLaplacianDamping = 2.5f;
    // Purely tangential mesh regularization keeps material rings distributed
    // along the meridian; it does not define a target geometric shape.
    float meshRegularization = 0.10f;
    float tangentialRedistributionRate = 3.0f;
    // Reparameterize only after the physical edge-length ratio becomes poor.
    // Curvature-weighted arc length retains extra rings in the neck.
    float resamplingEdgeRatio = 2.35f;
    float resamplingCurvatureWeight = 1.20f;
    // Lowest axisymmetric capillary (quadrupole) mode. This contributes an
    // acceleration field, never a positional morph or target profile.
    float globalModeFrequency = 2.10f;
    float globalModeDampingRatio = 0.40f;
    // Position-level volume projection strength and iteration count.
    float volumeConstraintStrength = 0.92f;
    int volumeProjectionIterations = 4;
    // Initial radial velocity generated by rupture at the neck.
    float initialNeckExpansionSpeed = 0.42f;
    // Stable semi-implicit integration limits.
    float maximumTimeStep = 1.0f / 480.0f;
    int maximumSubsteps = 16;
    float maximumNodeSpeed = 1.65f;
};

struct FusionProfileDiagnostics {
    float volume = 0.0f;
    float area = 0.0f;
    float centroidZ = 0.0f;
    float rmsSpeed = 0.0f;
    float curvatureVariation = 0.0f;
    float minEdgeLength = 0.0f;
    float maxEdgeLength = 0.0f;
    float edgeLengthRatio = 1.0f;
    float minInternalAngleDegrees = 180.0f;
    float maxAbsCurvature = 0.0f;
    float maxNormalForce = 0.0f;
    float maxVolumeCorrection = 0.0f;
    int minAngleNode = -1;
    int maxCurvatureNode = -1;
    int maxNormalForceNode = -1;
    int maxVolumeCorrectionNode = -1;
    int maxEdgeNode = -1;
};

float FusionProfileVolume(const std::vector<FusionProfileNode>& nodes);
float FusionProfileArea(const std::vector<FusionProfileNode>& nodes);
float FusionProfileCentroidZ(const std::vector<FusionProfileNode>& nodes);

// Removes only grid-scale curvature jumps around the freshly opened neck.
// It is a one-time, volume-constrained surface fairing pass, not a target
// shape update.
void FairInitialFusionProfile(std::vector<FusionProfileNode>& nodes,
                              float neckZ,
                              float fairingHalfWidth,
                              int iterations);

// Advances the same persistent nodes in place.  There is deliberately no
// target sphere/profile argument: the sphere emerges by minimizing area at
// fixed volume.
FusionProfileDiagnostics AdvanceFusionProfile(
    std::vector<FusionProfileNode>& nodes,
    float targetVolume,
    float dt,
    const FusionProfileConfig& config);

#endif
